# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure_build

resources:
  containers:
  - container: ubuntu
    image: ubuntu:18.04

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: apt-get install -y build-essential cmake libffi-dev libgtk-3-dev git python3-dev python3.7-dev clang
  displayName: 'Install Build Deps'

- script: |
    cmake .
    make
  displayName: 'Build'
